name: phosphor_flutter
description: Implementation of Phosphoricons for Flutter. 772 icons and counting. Thin, Light, Regular, Bold, Fill.
version: 2.0.1
maintainer: Rurick Maqueo Poisot @rurickdev
homepage: https://phosphoricons.com/
repository: https://github.com/phosphor-icons/phosphor-flutter
screenshots:
  - description: Regular style icons
    path: meta/screenshot_regular.png
  - description: Thin style icons
    path: meta/screenshot_thin.png
  - description: Light style icons
    path: meta/screenshot_light.png
  - description: Bold style icons
    path: meta/screenshot_bold.png
  - description: Fill style icons
    path: meta/screenshot_fill.png
  - description: Duotone style icons
    path: meta/screenshot_duotone.png

environment:
  sdk: "^2.12.0"
  flutter: "^1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: PhosphorBold
      fonts:
        - asset: lib/fonts/Phosphor-Bold.ttf
          weight: 400
    - family: PhosphorDuotone
      fonts:
        - asset: lib/fonts/Phosphor-Duotone.ttf
          weight: 400
    - family: PhosphorFill
      fonts:
        - asset: lib/fonts/Phosphor-Fill.ttf
          weight: 400
    - family: PhosphorLight
      fonts:
        - asset: lib/fonts/Phosphor-Light.ttf
          weight: 400
    - family: PhosphorThin
      fonts:
        - asset: lib/fonts/Phosphor-Thin.ttf
          weight: 400
    - family: PhosphorRegular
      fonts:
        - asset: lib/fonts/Phosphor.ttf
          weight: 400
